app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('user-home', views.user_home, name='user_home'),
    path('play/', views.play, name='play'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('submission-result/<int:attempted_question_pk>/', views.submission_result, name='submission_result'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('add-question/', views.add_question, name='add_question'),

]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel


class Question(TimeStampedModel):
    ALLOWED_NUMBER_OF_CORRECT_CHOICES = 1

    html = models.TextField(_('Question Text'))
    is_published = models.BooleanField(_('Has been published?'), default=False, null=False)
    maximum_marks = models.DecimalField(_('Maximum Marks'), default=4, decimal_places=2, max_digits=6)
    category = models.ForeignKey('Category',  on_delete=models.CASCADE)

    def __str__(self):
        return self.html


class Choice(TimeStampedModel):
    MAX_CHOICES_COUNT = 4

    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(_('Is this answer correct?'), default=False, null=False)
    html = models.TextField(_('Choice Text'))

    def __str__(self):
        return self.html


class QuizProfile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_score = models.DecimalField(_('Total Score'), default=0, decimal_places=2, max_digits=10)

    def __str__(self):
        return f'<QuizProfile: user={self.user}>'

    def get_new_question(self):
        used_questions_pk = AttemptedQuestion.objects.filter(quiz_profile=self).values_list('question__pk', flat=True)
        remaining_questions = Question.objects.exclude(pk__in=used_questions_pk)
        if not remaining_questions.exists():
            return
        return random.choice(remaining_questions)

    def create_attempt(self, question):
        attempted_question = AttemptedQuestion(question=question, quiz_profile=self)
        attempted_question.save()

    def evaluate_attempt(self, attempted_question, selected_choice):
        if attempted_question.question_id != selected_choice.question_id:
            return

        attempted_question.selected_choice = selected_choice
        if selected_choice.is_correct is True:
            attempted_question.is_correct = True
            attempted_question.marks_obtained = attempted_question.question.maximum_marks

        attempted_question.save()
        self.update_score()

    def update_score(self):
        marks_sum = self.attempts.filter(is_correct=True).aggregate(
            models.Sum('marks_obtained'))['marks_obtained__sum']
        self.total_score = marks_sum or 0
        self.save()


class AttemptedQuestion(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz_profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='attempts')
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(_('Was this attempt correct?'), default=False, null=False)
    marks_obtained = models.DecimalField(_('Marks Obtained'), default=0, decimal_places=2, max_digits=6)

    def get_absolute_url(self):
        return f'/submission-result/{self.pk}/'


class Category(models.Model):
    category_name = models.CharField(max_length=200, null=False)

    def __str__(self):
        return self.category_name

templates/quiz/1.html
<form method="post">
    <label for="id_html">Question Text:</label>
<br>
  <textarea name="html" cols="40" rows="10" required="" id="id_html"></textarea>
    <label for="id_is_published">Has been published?</label>
      <input type="checkbox" name="is_published" id="id_is_published">
            <input type="hidden" name="choices-TOTAL_FORMS" value="4" id="id_choices-TOTAL_FORMS"><input type="hidden" name="choices-INITIAL_FORMS" value="0" id="id_choices-INITIAL_FORMS"><input type="hidden" name="choices-MIN_NUM_FORMS" value="0" id="id_choices-MIN_NUM_FORMS"><input type="hidden" name="choices-MAX_NUM_FORMS" value="1000" id="id_choices-MAX_NUM_FORMS">
    <label for="id_choices-0-html">Choice Text:</label>

      <textarea name="choices-0-html" cols="80" rows="2" id="id_choices-0-html"></textarea>
     <label for="id_choices-0-is_correct">Is this answer correct?</label>

      <input type="checkbox" name="choices-0-is_correct" id="id_choices-0-is_correct">

        <input type="hidden" name="choices-0-id" id="id_choices-0-id"><input type="hidden" name="choices-0-question" id="id_choices-0-question">

    <label for="id_choices-1-html">Choice Text:</label>

      <textarea name="choices-1-html" cols="80" rows="2" id="id_choices-1-html"></textarea>

    <label for="id_choices-1-is_correct">Is this answer correct?</label>


      <input type="checkbox" name="choices-1-is_correct" id="id_choices-1-is_correct">


        <input type="hidden" name="choices-1-id" id="id_choices-1-id"><input type="hidden" name="choices-1-question" id="id_choices-1-question">

    <label for="id_choices-2-html">Choice Text:</label>


      <textarea name="choices-2-html" cols="80" rows="2" id="id_choices-2-html"></textarea>

    <label for="id_choices-2-is_correct">Is this answer correct?</label>


      <input type="checkbox" name="choices-2-is_correct" id="id_choices-2-is_correct">


        <input type="hidden" name="choices-2-id" id="id_choices-2-id"><input type="hidden" name="choices-2-question" id="id_choices-2-question">



    <label for="id_choices-3-html">Choice Text:</label>


      <textarea name="choices-3-html" cols="80" rows="2" id="id_choices-3-html"></textarea>

    <label for="id_choices-3-is_correct">Is this answer correct?</label>


      <input type="checkbox" name="choices-3-is_correct" id="id_choices-3-is_correct">


        <input type="hidden" name="choices-3-id" id="id_choices-3-id"><input type="hidden" name="choices-3-question" id="id_choices-3-question">

            <input type="submit" value="Submit">
        </form>

templates/quiz/add_question.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron container row">
    <div class="col-md-6">
        <h1>Add Question</h1>

        <form method="post">
            {% csrf_token %}

            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.label_tag }}
                    {% if not field.name == 'is_published' %}
                        <br/>
                    {% endif %}
                    {{ field }}
                </div>
                {% endfor %}

            {{ formset }}
            <br/>
            <input type="submit" value="Submit">

        </form>
    </div>

</div>

{% endblock %}

templates/quiz/error_404.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Page does not exists {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Error 404: Page not found</h4>
	          <p>The page you are looking does not exist. <a href="{% url 'quiz:home' %}" class="alert-link">Go back to homepage</a></p>
        </div>
    </div>

{% endblock content %}

templates/quiz/error_500.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Internal Server Error {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Internal Server Error</h4>
	          <p>There is some error in internal server, we will be back soon.</p>
        </div>
    </div>

{% endblock content %}

templates/quiz/home.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Home {% endblock title %}
{% block content %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">ITechArt Quiz</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>

        {% if not request.user.is_active %}

        <p class="lead">Sign up if you haven't already and get access to millions of quizzes on the topic of your interest.</p>
        <p><strong> Start Your Journey Here:</strong></p>
        <a href="{% url 'app:register' %}" class="btn btn-lg btn-info mt-1"><i class="fa fa-user-plus" aria-hidden="true"></i> Sign Up</a>

        {% else %}
        <a href="{% url 'app:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'app:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
        {% if request.user.is_staff %}
        <a href="{% url 'app:add_question' %}" class="btn btn-lg btn-info mt-1">Add Question</a>
        {% endif %}
        {% endif %}
      </div>
    </section>

{% endblock content %}

templates/quiz/leaderboard.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Leaderboard {% endblock title %}
{% block content %}
<div class="container">
    <h1 class="text-center my-4"><span class="badge badge-info"><i class="fa fa-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_profile in top_quiz_profiles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ quiz_profile.user.username }}</td>
                <td>{{ quiz_profile.total_score }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/quiz/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} ITechArt Quiz | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Please log in</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-info btn-block" value="{{ title }}">
                </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'app:register' %}" class="btn btn-success mb-3">Create account</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">ITechArt Quiz</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <a href="{% url 'app:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'app:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
      </div>
    </section>

{% endif %}

{% endblock content %}

templates/quiz/play.html
{% extends 'base.html' %}

{% block content %}
{% if question is None %}

<div class="container">
  <div class="jumbotron my-4">
    <h1> You have already answered all of our questions. </h1>
    <a href="{% url 'app:leaderboard' %}" class="btn btn-lg btn-info"><i class="fa fa-trophy" aria-hidden="true"></i> See the leaderboard here <i class="fa fa-trophy" aria-hidden="true"></i></a>
  </div>
</div>

{% else %}

<div class="container">
  <div class="jumbotron my-4">

    <h3 class="text-info">{{ question.html|safe }}</h3>
    <form class="form" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="question_pk" value="{{ question.pk }}">
        {% for choice in question.choices.all %}
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="choice_pk" id="choice-{{ forloop.counter }}" value="{{ choice.pk }}">
            <label class="form-check-label" for="choice-{{ forloop.counter }}">
              {{ choice.html|safe }}
            </label>
          </div>

        {% endfor %}
        <input class="btn btn-info btn-lg" type="submit" value="Submit">
    </form>
  </div>
</div>
{% endif %}

{% endblock content %}

templates/quiz/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} ITechArt Quiz | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

     <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Create a new account</h1>
              <form class="mb-3" method="POST" action="">
                {% csrf_token %}
		        {{form|crispy}}
		        <input type="submit" class="btn btn-info btn-block mb-3" value="{{ title }}">
              </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'app:login' %}" class="btn btn-success">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>

{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">ITechArt Quiz</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <a href="{% url 'app:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'app:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
      </div>
    </section>

{% endif %}

{% endblock content %}

templates/quiz/submission_result.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Submission Result {% endblock title %}
{% block content %}
<div class="container">
	<div class="jumbotron my-4">

	   	<h3 class="text-info">{{ attempted_question.question.html|safe }}</h3>

		<p>
		    <strong>Your answer: </strong>
		    {{ attempted_question.selected_choice.html|safe }}
		</p>

		{% if attempted_question.selected_choice.is_correct %}
		<h4 class="text-success">Yayy!! Your answer is correct. High Five! 🙌</h4>
		{% else %}
		<h4 class="text-danger">Your answer is incorrect 😟</h4>
		{% endif %}

		<a class="btn btn-info" href="{% url 'app:play' %}">Show next question</a>
	</div>
</div>

{% endblock content %}

templates/quiz/user_home.html
{% extends 'base.html' %}
{% block title %} ITechArt Quiz | Welcome {% endblock title %}
{% block content %}
<div class="container my-4">
    <div class="jumbotron">

	      <h2 class="text-center text-info">Congratulations!! You have successfully logged in.</h2>
	      <h3 class="text-info text-center">Before you play the quiz, here are the rules</h3>

        <div class="row">

            <div class="card border-info mx-4 my-4">
                <div class="card-body text-info">
                    <h4 class="card-title">Rules :</h4>
                    <p class="card-text">
                        <ul style="list-style:decimal;">
                            <li>All questions are multiple choice question.</li>
                            <li><span class="text-danger">Only one choice is correct.</span></li>
                            <li>Every question carry equal marks i.e. <span class="text-danger">4 marks for each question.</span>
                            </li>
                            <li>Every question is displayed only once per user.</li>
                            <li>Try to answer as quickly as you can.</li>
                            <li>If you press refresh or go back to the previous page, there will be a new question for you and the question you were on will be counted as attempted.</li>
                            <li>Questions are displayed randomly for every user.</li>
                            <li>You will be told immediately whether your answer was correct or incorrect once you submit the answer.</li>
                        </ul>
                    </p>
                    <a href="{% url 'app:play' %}" class="btn btn-info">Let's play</a>
                </div>
                <div class="card-footer">Rules last modified 06-September-2022</div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}